package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_projects",
    srcs = [
        "//cpp-momentum-service:pulseboard_cpp",
        "//java-focus-planner:pulseboard_java",
        "//android-pulseboard:android_project_bundle",
        "//ios-pulseboard:ios_project_bundle",
    ],
)
