load("@rules_java//java:defs.bzl", "java_binary", "java_test")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "pulseboard_java",
    srcs = ["src/Main.java"],
    main_class = "Main",
)

java_test(
    name = "pulseboard_java_test",
    srcs = ["test/UnitTest.java"],
    main_class = "UnitTest",
    use_testrunner = False,
)
